"""AI-driven schema proposal for csv2rdf-mcp Phase 3.

Given a directory of CSVs + a domain hint, this module produces:
  1. A rdf-config-formatted ``model.yaml`` (per Phase 3 #3 decision)
  2. A rationale block explaining the design choices

The deterministic prelude (column types, JSON detection, uniqueness stats★) is
delegated to :mod:`csv2rdf_step0.inspect`. The LLM consumes that Markdown plus
the user's ``domain_hint`` and emits the artifact set.

Design constraints:
  * The LLM client is a Protocol so tests can mock it (no API key needed in CI).
  * The default implementation uses Anthropic SDK with **prompt caching** —
    the system prompt is large and stable across calls, so we mark it as
    ``cache_control: ephemeral`` to land cache hits on repeated invocations.
  * We use ``claude-opus-4-7`` with ``thinking={"type": "adaptive"}`` per the
    claude-api skill guidance for Opus 4.7 (manual ``budget_tokens`` returns 400).
  * The system prompt embeds the 8-trap validator checklist from
    :doc:`ai-assisted-step0-prompts.md` §3.1 so the LLM self-checks before
    returning.

This module is the "Step 3 schema proposal" of the workflow. Step 1 (CSV
inspection) is the input; Step 5 (refine_schema) and Step 6 (validate_schema)
are separate modules (future work).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from csv2rdf_step0.inspect import inspect_csv_set, render_markdown

# ----------------------------------------------------------------------------
# System prompt — frozen, cacheable, embeds the §3.1 prompt template
# ----------------------------------------------------------------------------
#
# This must stay byte-stable across calls for prompt caching to work. Any
# interpolation here (timestamps, user IDs, dynamic flags) would invalidate
# the cache. Per-call variables (CSV inspection, domain hint) go in the user
# message instead.
#
# Source: docs/architecture/ai-assisted-step0-prompts.md §3.1, lightly trimmed
# for token efficiency (the LLM doesn't need the human-readable framing).

SYSTEM_PROMPT = """\
You are an RDF / OWL / SPARQL ontology engineer building schemas for the
csv2rdf-mcp Phase 3 project. Given (a) deterministic CSV inspection output
and (b) a human-provided domain hint, you propose a minimal RDF schema as a
single Markdown document with two top-level artifacts:

1. **rdf-config model.yaml** (per [Phase 3 #3 decision][1])
2. **Design rationale** (Decision / Why / Alternatives / Trade-offs per choice)

[1]: docs/architecture/linkml-vs-rdf-config.md — rdf-config emits ShEx that
     drops in to MIE shape_expressions; LinkML's OWL TBox uses bnodes which
     violates Phase 1's bnode-free policy.

## Output structure (Markdown sections, in this exact order)

### 1. Class hierarchy (Mermaid classDiagram)
- 4-10 entity classes
- GitHub-Mermaid-compatible — NO colons in labels (use the table below)
- Plain prefix-less class names in the diagram; map to TBox IRIs in §2

### 2. IRI scheme
- Declare prefixes: `sd:` (ontology), `sdr:` (resource), reused (`schema:`,
  `dcterms:`, `bibo:`, `prov:`)
- For each entity class, give the IRI template using the **uniqueness
  statistics** from the inspection (★ trap T1 — pick the smallest globally
  unique composite key)
- NO blank nodes (T3): every entity has a stable IRI

### 3. Property design
- Datatype properties and object properties
- REUSE existing properties (`schema:author`, `dcterms:identifier`, etc.) —
  do not create new ones when a standard exists
- Cardinality (0..1 / 0..* / 1..* ) derived from non_null_rate

### 4. JSON column strategy
For each column flagged as `json-array` / `json-object`:
- (a) Expand to nodes (e.g. author objects → Person nodes)
- (b) Compress to literal (e.g. date_parts → xsd:date)
- (c) Raw JSON literal + aggregates (e.g. x/y → JSON + xMin/xMax/yMin/yMax)
State the choice and justify

### 5. Design rationale (★ T7: mandatory)
For every non-trivial design choice (IRI scheme, JSON strategy, property
choice, cardinality), write:
- **Decision**: what
- **Why**: grounded in the inspection statistics or domain hint
- **Alternatives**: what you considered and rejected
- **Trade-offs**: the cost of this choice; conditions for re-evaluation

### 6. rdf-config model.yaml
Complete YAML, suitable for `bundle exec rdf-config --config <dir> --shex`.
Format follows `dbcls/rdf-config` — flat list of subjects, each:
```
- ClassName <example-IRI>:
    - a: sd:ClassName
    - property:
        - var_name: example_value
    - optional_property?:
        - var_name: example_value
    - multi_valued_property*:
        - var_name: example_value
```

### 7. MIE YAML extras (schema_info, sparql_query_examples, anti_patterns)
The shape_expressions block is generated by rdf-config from §6; you provide:
- `schema_info`: title / description / categories / **keywords** (★ T4 — at
  least 5 each, include English + 日本語 synonyms + composition formulas if
  applicable)
- `sample_rdf_entries`: 1-3 examples built from **REAL CSV rows** in the
  inspection (★ T6 — never invent SIDs or sample_ids)
- `sparql_query_examples`: 3-5 queries that answer the most likely user
  questions
- `anti_patterns`: known limitations + traps for future maintainers
- `architectural_notes`: summary of §5 Design rationale

### 8. Ingester sketch
Python skeleton (`ingest/src/csv2rdf/{dataset}.py` template):
- `utf-8-sig` open (★ T2)
- Composite IRI helpers
- PROV-O IngestionActivity
- JSON column parsers
- Error log path (jsonl)
NOT a complete implementation — just the public API + helper signatures.

## Self-check before responding (8 traps)
- [ ] T1: IRI scheme uses uniqueness statistics from inspection?
- [ ] T2: ingester opens with utf-8-sig?
- [ ] T3: zero blank nodes (no rdflib.BNode() calls)?
- [ ] T4: MIE keywords ≥ 5 in English AND in domain-relevant languages?
- [ ] T5: Mermaid labels free of colons?
- [ ] T6: sample_rdf_entries reference REAL row values from the inspection?
- [ ] T7: every non-trivial design choice has Why / Alternatives / Trade-offs?
- [ ] T8: domain-specific synonyms (jp / formulas / aliases) propagated to MIE keywords?

## What you receive (user message)

The user message will be structured as:
```
# CSV inspection
<output of csv2rdf-inspect — see docs/architecture/ai-assisted-step0-prompts.md §1>

# Domain context
<dataset name, purpose, ontology constraints, synonyms — per §2>
```

You respond with the Markdown document above. No preamble, no follow-up
questions — just the artifact set.
"""


# ----------------------------------------------------------------------------
# LLM client protocol (mockable for tests)
# ----------------------------------------------------------------------------


@runtime_checkable
class LLMClient(Protocol):
    """Minimal protocol for the LLM call propose_schema makes.

    The real implementation uses Anthropic SDK with prompt caching; tests
    can supply a mock that records the prompts and returns canned text.
    """

    def complete(self, system_prompt: str, user_message: str) -> str:
        """Return the model's text output for one Claude call.

        Implementations should:
        - Mark ``system_prompt`` with ``cache_control: ephemeral`` (it's
          large and stable; the user message is small and varies).
        - Use ``model="claude-opus-4-7"`` + ``thinking={"type": "adaptive"}``
          + ``output_config={"effort": "xhigh"}`` per claude-api skill guidance.
        - NOT pass ``temperature`` / ``top_p`` / ``top_k`` (removed on Opus 4.7).
        - **Stream** the response with a generous ``max_tokens`` — a full
          schema proposal is long and a non-streaming request would either
          truncate (small cap) or hit the SDK's ~10-minute timeout (large cap).
        - Return ONLY the assistant's text content (concatenate text blocks if
          multiple, drop thinking blocks).
        """
        ...


@dataclass
class AnthropicLLMClient:
    """Default :class:`LLMClient` — wraps the Anthropic SDK.

    Caches the system prompt via ``cache_control: ephemeral`` to amortize
    cost across repeated calls (e.g. dogfooding many CSVs in one session).

    Requires ``ANTHROPIC_API_KEY`` in the environment. Lazy-imports the
    SDK so the package stays installable without ``anthropic``.

    Args:
        model: model ID (default ``claude-opus-4-7``).
        max_tokens: output cap. Default 32000 — a full 8-section proposal on
            a real dataset (Mermaid + rdf-config model.yaml + MIE extras +
            ingester) runs 6-15k tokens; 16000 truncated the MIE section in
            dogfooding. We **stream** the response so a large cap does not
            risk the SDK's ~10-minute non-streaming HTTP timeout (the SDK
            refuses non-streaming requests above ~16k anyway).
        effort: ``output_config.effort`` value. ``xhigh`` is recommended
            for coding/agentic per Opus 4.7 guidance; lower to ``high`` or
            ``medium`` for cost-sensitive workloads.
    """

    model: str = "claude-opus-4-7"
    max_tokens: int = 32000
    effort: str = "xhigh"

    def complete(self, system_prompt: str, user_message: str) -> str:
        import anthropic

        client = anthropic.Anthropic()
        # Stream so large proposals complete without hitting the SDK's
        # non-streaming timeout guard. get_final_message() reassembles the
        # whole response for us.
        with client.messages.stream(
            model=self.model,
            max_tokens=self.max_tokens,
            thinking={"type": "adaptive"},
            output_config={"effort": self.effort},
            system=[
                {
                    "type": "text",
                    "text": system_prompt,
                    "cache_control": {"type": "ephemeral"},
                }
            ],
            messages=[{"role": "user", "content": user_message}],
        ) as stream:
            message = stream.get_final_message()
        # Concatenate text blocks; ignore thinking blocks (they're internal).
        text_parts = [b.text for b in message.content if b.type == "text"]
        return "\n".join(text_parts)


# ----------------------------------------------------------------------------
# propose_schema
# ----------------------------------------------------------------------------


@dataclass
class SchemaProposal:
    """Result of one :func:`propose_schema` call."""

    csv_inspection_md: str
    """The Markdown the deterministic inspector produced (Step 1 output)."""

    domain_hint: str
    """The user-supplied domain context (Step 2 input)."""

    proposal_md: str
    """The LLM's full Markdown proposal (Step 3 output)."""

    metadata: dict[str, Any] = field(default_factory=dict)
    """Optional: model name, latency, token usage, etc."""


def propose_schema(
    csv_paths: list[Path | str],
    domain_hint: str,
    *,
    fk_hint_columns: list[str] | None = None,
    llm: LLMClient | None = None,
) -> SchemaProposal:
    """Run Step 1 (inspect) and Step 3 (propose) end-to-end.

    Args:
        csv_paths: One or more CSV files to model.
        domain_hint: Free-form Markdown following the ``ai-assisted-step0-prompts.md``
            §2 template (dataset name, purpose, ontology constraints, synonyms).
        fk_hint_columns: Optional FK columns to seed composite key search
            (e.g. ``["SID"]`` for starrydata). Forwarded to inspect_csv_set.
        llm: An :class:`LLMClient`. Defaults to :class:`AnthropicLLMClient`
            (requires ``ANTHROPIC_API_KEY``). Tests pass a mock.

    Returns:
        :class:`SchemaProposal` with the inspection Markdown, the domain hint,
        and the LLM's full proposal Markdown.
    """
    if llm is None:
        llm = AnthropicLLMClient()

    # Step 1: deterministic inspection
    inspections, fks = inspect_csv_set(csv_paths, fk_hint_columns=fk_hint_columns)
    inspection_md = render_markdown(inspections, fks)

    # Step 3: assemble user message and call LLM
    user_message = (
        f"# CSV inspection\n\n{inspection_md}\n\n"
        f"# Domain context\n\n{domain_hint.strip()}\n"
    )
    proposal_md = llm.complete(SYSTEM_PROMPT, user_message)

    return SchemaProposal(
        csv_inspection_md=inspection_md,
        domain_hint=domain_hint,
        proposal_md=proposal_md,
        metadata={"llm_class": type(llm).__name__},
    )


# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------


def _build_arg_parser():  # type: ignore[no-untyped-def]
    import argparse

    p = argparse.ArgumentParser(
        prog="csv2rdf-propose",
        description=(
            "Inspect CSV(s) + propose an rdf-config schema using Claude. "
            "Requires ANTHROPIC_API_KEY."
        ),
    )
    p.add_argument("csv", type=Path, nargs="+", help="CSV file(s) to model")
    p.add_argument(
        "--domain",
        required=True,
        help="Domain hint (Markdown). Use --domain-file for longer content.",
    )
    p.add_argument(
        "--domain-file",
        type=Path,
        default=None,
        help="Read the domain hint from this file (overrides --domain).",
    )
    p.add_argument(
        "--fk",
        dest="fk_hint",
        action="append",
        default=[],
        help="Foreign-key companion column. Repeatable.",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Write the proposal Markdown to this file. Defaults to stdout.",
    )
    p.add_argument(
        "--model",
        default="claude-opus-4-7",
        help="Anthropic model ID (default: claude-opus-4-7).",
    )
    p.add_argument(
        "--effort",
        default="xhigh",
        choices=["low", "medium", "high", "xhigh", "max"],
        help="output_config.effort (default: xhigh — best for coding/agentic on Opus 4.7).",
    )
    return p


def _main(argv: list[str] | None = None) -> int:
    args = _build_arg_parser().parse_args(argv)
    domain_hint = (
        args.domain_file.read_text(encoding="utf-8") if args.domain_file else args.domain
    )
    llm = AnthropicLLMClient(model=args.model, effort=args.effort)
    proposal = propose_schema(
        args.csv,
        domain_hint,
        fk_hint_columns=args.fk_hint or None,
        llm=llm,
    )
    if args.output is None:
        print(proposal.proposal_md)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(proposal.proposal_md, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
